In [1]:
import pandas as pd
import numpy as np

import matplotlib.pyplot as plt

In [2]:
data = 'https://raw.githubusercontent.com/alexeygrigorev/mlbookcamp-code/master/chapter-03-churn-prediction/WA_Fn-UseC_-Telco-Customer-Churn.csv'

zsh:1: command not found: wget

In [3]:
url = 'https://raw.githubusercontent.com/alexeygrigorev/mlbookcamp-code/master/chapter-03-churn-prediction/WA_Fn-UseC_-Telco-Customer-Churn.csv'

df = pd.read_csv(url)
df.to_csv('data-week-3.csv', index=False)

print(df.head())

   customerID  gender  SeniorCitizen Partner Dependents  tenure PhoneService  \
0  7590-VHVEG  Female              0     Yes         No       1           No
1  5575-GNVDE    Male              0      No         No      34          Yes
2  3668-QPYBK    Male              0      No         No       2          Yes
3  7795-CFOCW    Male              0      No         No      45           No
4  9237-HQITU  Female              0      No         No       2          Yes

      MultipleLines InternetService OnlineSecurity  ... DeviceProtection  \
0  No phone service             DSL             No  ...               No
1                No             DSL            Yes  ...              Yes
2                No             DSL            Yes  ...               No
3  No phone service             DSL            Yes  ...              Yes
4                No     Fiber optic             No  ...               No

  TechSupport StreamingTV StreamingMovies        Contract PaperlessBilling  \
0          No          No              No  Month-to-month              Yes
1          No          No              No        One year               No
2          No          No              No  Month-to-month              Yes
3         Yes          No              No        One year               No
4          No          No              No  Month-to-month              Yes

               PaymentMethod MonthlyCharges  TotalCharges Churn
0           Electronic check          29.85         29.85    No
1               Mailed check          56.95        1889.5    No
2               Mailed check          53.85        108.15   Yes
3  Bank transfer (automatic)          42.30       1840.75    No
4           Electronic check          70.70        151.65   Yes

[5 rows x 21 columns]

In [4]:
df.columns = df.columns.str.lower().str.replace(' ', '_')

categorical_columns = list(df.dtypes[df.dtypes == 'object'].index)

for c in categorical_columns:
    df[c] = df[c].str.lower().str.replace(' ', '_')

In [5]:
df.dtypes

customerid              str
gender                  str
seniorcitizen         int64
partner                 str
dependents              str
tenure                int64
phoneservice            str
multiplelines           str
internetservice         str
onlinesecurity          str
onlinebackup            str
deviceprotection        str
techsupport             str
streamingtv             str
streamingmovies         str
contract                str
paperlessbilling        str
paymentmethod           str
monthlycharges      float64
totalcharges            str
churn                   str
dtype: object

In [6]:
pd.to_numeric(df.totalcharges)

ValueError: Unable to parse string " " at position 488

In [7]:
tc = pd.to_numeric(df.totalcharges, errors='coerce')

In [8]:
tc.isnull().sum()

np.int64(11)

In [9]:
df[tc.isnull()][['customerid', 'totalcharges']]

      customerid totalcharges
488   4472-LVYGI
753   3115-CZMZD
936   5709-LVOEQ
1082  4367-NUYAO
1340  1371-DWPAZ
3331  7644-OMVMY
3826  3213-VVOLG
4380  2520-SGTTA
5218  2923-ARZLG
6670  4075-WKNIU
6754  2775-SEFEE

In [10]:
df.totalcharges = pd.to_numeric(df.totalcharges, errors='coerce')
df.totalcharges = df.totalcharges.fillna(0)

In [11]:
df.churn.head()

0     No
1     No
2    Yes
3     No
4    Yes
Name: churn, dtype: str

In [12]:
df.churn = (df.churn == 'yes').astype(int)

In [13]:
from sklearn.model_selection import train_test_split

In [14]:
df_full_train, df_test = train_test_split(df, test_size=0.2, random_state=1)

In [15]:
df_train, df_val = train_test_split(df_full_train, test_size=0.25, random_state=1)

In [16]:
len(df_train), len(df_val), len(df_test)

(4225, 1409, 1409)

In [17]:
df_train = df_train.reset_index(drop=True)
df_val = df_val.reset_index(drop=True)
df_test = df_test.reset_index(drop=True)

In [18]:
y_train = df_train.churn.values
y_val = df_val.churn.values
y_test = df_test.churn.values

In [19]:
del df_train['churn']
del df_val['churn']
del df_test['churn']

In [20]:
df_train.churn

AttributeError: 'DataFrame' object has no attribute 'churn'

In [21]:
df_train.churn.values

AttributeError: 'DataFrame' object has no attribute 'churn'

In [22]:
df_full_train = df_full_train.reset_index(drop=True)

In [23]:
df_full_train.isnull().sum()

customerid          0
gender              0
seniorcitizen       0
partner             0
dependents          0
tenure              0
phoneservice        0
multiplelines       0
internetservice     0
onlinesecurity      0
onlinebackup        0
deviceprotection    0
techsupport         0
streamingtv         0
streamingmovies     0
contract            0
paperlessbilling    0
paymentmethod       0
monthlycharges      0
totalcharges        0
churn               0
dtype: int64

In [24]:
df_full_train.churn.value_counts(normalize=True)

churn
0    1.0
Name: proportion, dtype: float64

In [25]:
df_full_train.churn.mean()

np.float64(0.0)

In [26]:
numerical = ['tenure', 'monthlycharges', 'totalcharges']

In [27]:
categorical = [
    'gender',
    'seniorcitizen',
    'partner',
    'dependents',
    'phoneservice',
    'multiplelines',
    'internetservice',
    'onlinesecurity',
    'onlinebackup',
    'deviceprotection',
    'techsupport',
    'streamingtv',
    'streamingmovies',
    'contract',
    'paperlessbilling',
    'paymentmethod',
]

In [28]:
df_full_train[categorical].nunique()

gender              2
seniorcitizen       2
partner             2
dependents          2
phoneservice        2
multiplelines       3
internetservice     3
onlinesecurity      3
onlinebackup        3
deviceprotection    3
techsupport         3
streamingtv         3
streamingmovies     3
contract            3
paperlessbilling    2
paymentmethod       4
dtype: int64

In [29]:
global_churn = df_full_train.churn.mean()

In [30]:
global_churn

np.float64(0.0)

In [31]:
df_full_train

,customerid,gender,seniorcitizen,partner,dependents,tenure,phoneservice,multiplelines,internetservice,onlinesecurity,...,deviceprotection,techsupport,streamingtv,streamingmovies,contract,paperlessbilling,paymentmethod,monthlycharges,totalcharges,churn
0,5442-PPTJY,Male,0,Yes,Yes,12,Yes,No,No,No internet service,...,No internet service,No internet service,No internet service,No internet service,Two year,No,Mailed check,19.70,258.35,0
1,6261-RCVNS,Female,0,No,No,42,Yes,No,DSL,Yes,...,Yes,Yes,No,Yes,One year,No,Credit card (automatic),73.90,3160.55,0
2,2176-OSJUV,Male,0,Yes,No,71,Yes,Yes,DSL,Yes,...,No,Yes,No,No,Two year,No,Bank transfer (automatic),65.15,4681.75,0
3,6161-ERDGD,Male,0,Yes,Yes,71,Yes,Yes,DSL,Yes,...,Yes,Yes,Yes,Yes,One year,No,Electronic check,85.45,6300.85,0
4,2364-UFROM,Male,0,No,No,30,Yes,No,DSL,Yes,...,No,Yes,Yes,No,One year,No,Electronic check,70.40,2044.75,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5629,0781-LKXBR,Male,1,No,No,9,Yes,Yes,Fiber optic,No,...,Yes,No,Yes,Yes,Month-to-month,Yes,Electronic check,100.50,918.60,0
5630,3507-GASNP,Male,0,No,Yes,60,Yes,No,No,No internet service,...,No internet service,No internet service,No internet service,No internet service,Two year,No,Mailed check,19.95,1189.90,0
5631,8868-WOZGU,Male,0,No,No,28,Yes,Yes,Fiber optic,No,...,Yes,No,Yes,Yes,Month-to-month,Yes,Electronic check,105.70,2979.50,0
5632,1251-KRREG,Male,0,No,No,2,Yes,Yes,DSL,No,...,No,No,No,No,Month-to-month,Yes,Mailed check,54.40,114.10,0
5633,5840-NVDCG,Female,0,Yes,Yes,16,Yes,No,DSL,Yes,...,No,Yes,No,Yes,Two year,No,Bank transfer (automatic),68.25,1114.85,0

In [32]:
churn_female = df_full_train[df_full_train.gender == 'female'].churn.mean()
churn_male = df_full_train[df_full_train.gender == 'male'].churn.mean()

In [33]:
churn_female

nan

In [34]:
churn_male

nan

In [35]:
churn_female = df_full_train[df_full_train.gender == 'Female'].churn.mean()
churn_male = df_full_train[df_full_train.gender == 'Male'].churn.mean()

In [36]:
churn_female
churn_male

np.float64(0.0)

In [37]:
churn_female

np.float64(0.0)

In [38]:
global_churn - churn_female

np.float64(0.0)

In [39]:
df_full_train.partner.value_counts()

partner
No     2932
Yes    2702
Name: count, dtype: int64

In [40]:
churn_partner = df_full_train[df_full_train.partner == 'yes'].churn.mean()
churn_no_partner = df_full_train[df_full_train.partner == 'no'].churn.mean()

In [41]:
global_churn - churn_partner     =  0.06493474245795922
global_churn - churn_no_partner  = -0.05984095297455855

SyntaxError: cannot assign to expression here. Maybe you meant '==' instead of '='? (3712552787.py, line 1)

In [42]:
churn_no_partner / global_churn

np.float64(nan)

In [43]:
SELECT
    gender,
    AVG(churn),
    AVG(churn) - global_churn AS diff,
    AVG(churn) / global_churn AS risk
FROM
    data
GROUP BY
    gender;

IndentationError: unexpected indent (3578322304.py, line 2)

In [44]:
SELECT gender,
    AVG(churn),
    AVG(churn) - global_churn AS diff,
    AVG(churn) / global_churn AS risk
FROM
    data
GROUP BY
    gender;

SyntaxError: invalid syntax (440603315.py, line 1)

In [45]:
from IPython.display import display

for c in categorical:
    print(c)
    df_group = df_full_train.groupby(c).churn.agg(['mean', 'count'])
    df_group['diff'] = df_group['mean'] - global_churn
    df_group['risk'] = df_group['mean'] / global_churn
    display(df_group)
    print()
    print()

gender

        mean  count  diff  risk
gender
Female   0.0   2796   0.0   NaN
Male     0.0   2838   0.0   NaN

seniorcitizen

               mean  count  diff  risk
seniorcitizen
0               0.0   4722   0.0   NaN
1               0.0    912   0.0   NaN

partner

         mean  count  diff  risk
partner
No        0.0   2932   0.0   NaN
Yes       0.0   2702   0.0   NaN

dependents

            mean  count  diff  risk
dependents
No           0.0   3968   0.0   NaN
Yes          0.0   1666   0.0   NaN

phoneservice

              mean  count  diff  risk
phoneservice
No             0.0    547   0.0   NaN
Yes            0.0   5087   0.0   NaN

multiplelines

                  mean  count  diff  risk
multiplelines
No                 0.0   2700   0.0   NaN
No phone service   0.0    547   0.0   NaN
Yes                0.0   2387   0.0   NaN

internetservice

                 mean  count  diff  risk
internetservice
DSL               0.0   1934   0.0   NaN
Fiber optic       0.0   2479   0.0   NaN
No                0.0   1221   0.0   NaN

onlinesecurity

                     mean  count  diff  risk
onlinesecurity
No                    0.0   2801   0.0   NaN
No internet service   0.0   1221   0.0   NaN
Yes                   0.0   1612   0.0   NaN

onlinebackup

                     mean  count  diff  risk
onlinebackup
No                    0.0   2498   0.0   NaN
No internet service   0.0   1221   0.0   NaN
Yes                   0.0   1915   0.0   NaN

deviceprotection

                     mean  count  diff  risk
deviceprotection
No                    0.0   2473   0.0   NaN
No internet service   0.0   1221   0.0   NaN
Yes                   0.0   1940   0.0   NaN

techsupport

                     mean  count  diff  risk
techsupport
No                    0.0   2781   0.0   NaN
No internet service   0.0   1221   0.0   NaN
Yes                   0.0   1632   0.0   NaN

streamingtv

                     mean  count  diff  risk
streamingtv
No                    0.0   2246   0.0   NaN
No internet service   0.0   1221   0.0   NaN
Yes                   0.0   2167   0.0   NaN

streamingmovies

                     mean  count  diff  risk
streamingmovies
No                    0.0   2213   0.0   NaN
No internet service   0.0   1221   0.0   NaN
Yes                   0.0   2200   0.0   NaN

contract

                mean  count  diff  risk
contract
Month-to-month   0.0   3104   0.0   NaN
One year         0.0   1186   0.0   NaN
Two year         0.0   1344   0.0   NaN

paperlessbilling

                  mean  count  diff  risk
paperlessbilling
No                 0.0   2313   0.0   NaN
Yes                0.0   3321   0.0   NaN

paymentmethod

                           mean  count  diff  risk
paymentmethod
Bank transfer (automatic)   0.0   1219   0.0   NaN
Credit card (automatic)     0.0   1217   0.0   NaN
Electronic check            0.0   1893   0.0   NaN
Mailed check                0.0   1305   0.0   NaN

In [46]:
from sklearn.metrics import mutual_info_score

In [47]:
mutual_info_score(df_full_train.churn, df_full_train.contract)

0.0

In [48]:
def mutual_info_churn_score(series):
    return mutual_info_score(series, df_full_train.churn)

In [49]:
mi = df_full_train[categorical].apply(mutual_info_churn_score)
mi.sort_values(ascending=False)

gender              0.0
seniorcitizen       0.0
partner             0.0
dependents          0.0
phoneservice        0.0
multiplelines       0.0
internetservice     0.0
onlinesecurity      0.0
onlinebackup        0.0
deviceprotection    0.0
techsupport         0.0
streamingtv         0.0
streamingmovies     0.0
contract            0.0
paperlessbilling    0.0
paymentmethod       0.0
dtype: float64